"""Add massar_code to Student

Revision ID: a05f901a6929
Revises: 
Create Date: 2026-05-05 13:12:08.093125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a05f901a6929'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('massar_code_enc', sa.Text(), nullable=False))
    op.add_column('students', sa.Column('massar_code_hash', sa.String(length=64), nullable=False))
    
    # Initialize data to avoid unique constraint violations
    op.execute("UPDATE students SET massar_code_hash = UUID() WHERE massar_code_hash = ''")
    op.execute("UPDATE students SET massar_code_enc = 'migrated' WHERE massar_code_enc = ''")
    
    op.create_index(op.f('ix_students_massar_code_hash'), 'students', ['massar_code_hash'], unique=True)
    op.create_foreign_key(None, 'students', 'users', ['approved_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_index(op.f('ix_students_massar_code_hash'), table_name='students')
    op.drop_column('students', 'massar_code_hash')
    op.drop_column('students', 'massar_code_enc')
    # ### end Alembic commands ###
